apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kafka-deployment
  namespace: app
  labels:
    app: spring-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kafka
  template:
    metadata:
      labels:
        app: spring-kafka
    spec:
      dnsPolicy: Default
      containers:
        - name: spring-kafka-container
          image: docker.io/library/spring-kafka:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: spring-kafka-secret
                  key: mongodb-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: spring-kafka-config-map
                  key: mongodb_db_name
            - name: BROKER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: spring-kafka-secret
                  key: kafka_broker_endpoint
            - name: CLUSTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-kafka-secret
                  key: kafka_cluster_api_key
            - name: CLUSTER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-kafka-secret
                  key: kafka_cluster_api_secret
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 40
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 0 #(default)
            periodSeconds: 10 # default
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 0 #(default)
            periodSeconds: 3 #(default)
---
kind: Service
apiVersion: v1
metadata:
  name: spring-kafka-service
  namespace: app
spec:
  selector:
    app: spring-kafka
#  type: LoadBalancer # as marked as external service
  ports:
    - name: spring-kafka-service
      protocol: TCP
      port: 8080
      targetPort: 8080 # port of pod
#      nodePort: 30000 # so now browser will have access by this port
---
#kind: Service
#apiVersion: v1
#metadata:
#  name: default-http-backend
#  namespace: app
#spec:
#  type: NodePort
#  selector:
#    app: spring-kafka
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: ingress-spring-kafka-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-spring-kafka
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
#  defaultBackend:
#    service:
#      name: spring-kafka-service
#      port:
#        number: 8080
  ingressClassName: ingress-spring-kafka-class
  tls:
    - hosts:
      - kodir.babyshark.com
      secretName: app-secret-tls
  rules:
    - host: kodir.babyshark.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-kafka-service
                port:
                  number: 8080
